// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func basicsTest() {
    var leftNumber: Number

    leftNumber = Number(1, precision: 20) + Number(2, precision: 20)
    #expect(leftNumber.toDouble().similarTo(3))

    leftNumber = Number(2, precision: 20) * Number(4, precision: 20)
    #expect(leftNumber.toDouble().similarTo(8))

}
