// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func basicsPrecisionTest() {
    var leftNumber: Number

    leftNumber = Number(10000000000, precision: 20) + Number(3, precision: 20)
    #expect(leftNumber.toDouble().similarTo(10000000003))

    leftNumber = Number("10000000000000000000000", precision: 20) + Number(3, precision: 20)
    #expect(leftNumber.similarTo(Number("10000000000000000000003", precision: 20)))

    leftNumber = Number("1000000000000000000000000000000000000", precision: 20) + Number(3, precision: 20)
    #expect(leftNumber.similarTo(Number("1000000000000000000000000000000000003", precision: 20)))

}
