// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func basics3Test() {
    let calculator = Calculator(precision: 20)
    var result: String

    #expect(calculator.calc("4.0 sqr") == "16.0")
    #expect(calculator.calc("2.0 sqr") == "4.0")
    #expect(calculator.calc("5.0 cubed") == "125.0")
    #expect(calculator.calc("2.0 cubed") == "8.0")
    result = calculator.calc("1.0 exp")
    if let d = Double(result) {
        #expect(d.similarTo(Double("2.7183")!))
    } else {
        #expect(result == "valid")
    }
    result = calculator.calc("2.0 exp")
    if let d = Double(result) {
        #expect(d.similarTo(Double("7.3891")!))
    } else {
        #expect(result == "valid")
    }
    #expect(calculator.calc("3.0 exp2") == "8.0")
    #expect(calculator.calc("4.0 exp2") == "16.0")
    #expect(calculator.calc("1.0 exp10") == "10.0")
    #expect(calculator.calc("2.0 exp10") == "100.0")
    #expect(calculator.calc("1.0 changeSign") == "-1.0")
    #expect(calculator.calc("-1.0 changeSign") == "1.0")
    #expect(calculator.calc("2.0 rez") == "0.5")
    #expect(calculator.calc("4.0 rez") == "0.25")
    #expect(calculator.calc("5.0 fac") == "120.0")
    #expect(calculator.calc("3.0 fac") == "6.0")
    #expect(calculator.calc("zero") == "0.0")
    result = calculator.calc("pi")
    if let d = Double(result) {
        #expect(d.similarTo(Double("3.1416")!))
    } else {
        #expect(result == "valid")
    }
    result = calculator.calc("e")
    if let d = Double(result) {
        #expect(d.similarTo(Double("2.7183")!))
    } else {
        #expect(result == "valid")
    }
    #expect(calculator.calc("-3.0 abs") == "3.0")
    #expect(calculator.calc("9.0 sqrt") == "3.0")
    result = calculator.calc("8.0 sqrt3")
    if let d = Double(result) {
        #expect(d.similarTo(Double("2.0")!))
    } else {
        #expect(result == "valid")
    }
    result = calculator.calc("2.0 sqrt")
    if let d = Double(result) {
        #expect(d.similarTo(Double("1.4142")!))
    } else {
        #expect(result == "valid")
    }
    result = calculator.calc("3.0 zeta")
    if let d = Double(result) {
        #expect(d.similarTo(Double("1.2021")!))
    } else {
        #expect(result == "valid")
    }
    #expect(calculator.calc("1.0 ln") == "0.0")
    result = calculator.calc("2.0 ln")
    if let d = Double(result) {
        #expect(d.similarTo(Double("0.6931")!))
    } else {
        #expect(result == "valid")
    }
    #expect(calculator.calc("10.0 log10") == "1.0")
    #expect(calculator.calc("100.0 log10") == "2.0")
    #expect(calculator.calc("8.0 log2") == "3.0")
    #expect(calculator.calc("16.0 log2") == "4.0")
}
