// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func basics3Test() async {
    let calculator = Calculator(precision: 20)
    var temp: Double = 0.0

    #expect((await calculator.asString("4.0 sqr")) == "16")
    #expect((await calculator.asString("2.0 sqr")) == "4")
    #expect((await calculator.asString("5.0 cubed")) == "125")
    #expect((await calculator.asString("2.0 cubed")) == "8")
    temp = await calculator.asDouble("1.0 exp")
    #expect(temp.similarTo(2.7183))
    temp = await calculator.asDouble("2.0 exp")
    #expect(temp.similarTo(7.3891))
    #expect((await calculator.asString("3.0 exp2")) == "8")
    #expect((await calculator.asString("4.0 exp2")) == "16")
    #expect((await calculator.asString("1.0 exp10")) == "10")
    #expect((await calculator.asString("2.0 exp10")) == "100")
    #expect((await calculator.asString("1.0 +/-")) == "-1")
    #expect((await calculator.asString("-1.0 +/-")) == "1")
    #expect((await calculator.asString("2.0 rez")) == "0.5")
    #expect((await calculator.asString("4.0 rez")) == "0.25")
    #expect((await calculator.asString("5.0 fac")) == "120")
    #expect((await calculator.asString("3.0 fac")) == "6")
    #expect((await calculator.asString("zero")) == "0")
    temp = await calculator.asDouble("pi")
    #expect(temp.similarTo(3.1416))
    temp = await calculator.asDouble("e")
    #expect(temp.similarTo(2.7183))
    #expect((await calculator.asString("-3.0 abs")) == "3")
    #expect((await calculator.asString("9.0 sqrt")) == "3")
    temp = await calculator.asDouble("8.0 sqrt3")
    #expect(temp.similarTo(2))
    temp = await calculator.asDouble("2.0 sqrt")
    #expect(temp.similarTo(1.4142))
    temp = await calculator.asDouble("3.0 zeta")
    #expect(temp.similarTo(1.2021))
    #expect((await calculator.asString("1.0 ln")) == "0")
    temp = await calculator.asDouble("2.0 ln")
    #expect(temp.similarTo(0.6931))
    #expect((await calculator.asString("10.0 log10")) == "1")
    #expect((await calculator.asString("100.0 log10")) == "2")
    #expect((await calculator.asString("8.0 log2")) == "3")
    #expect((await calculator.asString("16.0 log2")) == "4")
}
