// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func calculatorTest() {
    let calculator = Calculator(precision: 20)

    #expect(calculator.evaluateString("1 + 2 x 3").string == "7")
    var temp: Double
    temp = calculator.asDouble("1 sin sin")
    #expect(temp.similarTo(0.745624141665))
    #expect(calculator.evaluateString("4.5").string == "4.5")
    calculator.press(MemoryOperation.clearM)
    #expect(calculator.lr.string == "4.5")
    calculator.press(MemoryOperation.addToM)
    #expect(calculator.lr.string == "4.5")
    calculator.press(MemoryOperation.addToM)
    #expect(calculator.lr.string == "4.5")
    calculator.press(MemoryOperation.addToM)
    #expect(calculator.lr.string == "4.5")
    calculator.press(MemoryOperation.addToM)
    #expect(calculator.lr.string == "4.5")
    calculator.press(MemoryOperation.recallM)
    #expect(calculator.lr.string == "18")
// clearing memory, no change to the display
    calculator.press(AuxOperation.clear)
    #expect(calculator.lr.string == "0")
    calculator.press(MemoryOperation.recallM)
    #expect(calculator.lr.string == "18")
    calculator.press(MemoryOperation.clearM)
    #expect(calculator.lr.string == "18")
    calculator.press(MemoryOperation.recallM)
    #expect(calculator.lr.string == "18")
    #expect(calculator.evaluateString("2 sqr").string == "4")
    #expect(calculator.evaluateString("2 sqr 5").string == "5")
    calculator.press(AuxOperation.clear)
    #expect(calculator.lr.string == "0")
    temp = calculator.asDouble("1 sin sin")
    #expect(temp.similarTo(0.745624141665))
    #expect(calculator.evaluateString("10 %").string == "0.1")
}
