// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func largeTest() {
    let calculator = Calculator(precision: 20)
    var temp: Double = 0.0

    #expect(calculator.asString("1e9") == "1000000000")
    #expect(calculator.asString("1e12") == "1000000000000")
    #expect(calculator.asString("1e15") == "1000000000000000")
    #expect(calculator.asString("1e18") == "1000000000000000000")
    #expect(calculator.asString("1e21") == "1000000000000000000000")
    #expect(calculator.asString("1e24") == "1000000000000000000000000")
    #expect(calculator.asString("1e48") == "1000000000000000000000000000000000000000000000000")
    calculator.maxOutputLength = 10
    #expect(calculator.asString("1e9") == "1000000000")
    #expect(calculator.asString("1e12") == "1.0e12")
    #expect(calculator.asString("1e15") == "1.0e15")
    #expect(calculator.asString("1e18") == "1.0e18")
    #expect(calculator.asString("1e21") == "1.0e21")
    #expect(calculator.asString("1e24") == "1.0e24")
    #expect(calculator.asString("1e48") == "1.0e48")
    #expect(calculator.asString("55555.1234567890") == "55555.1234")
    #expect(calculator.asString("555555.1234567890") == "555555.123")
    #expect(calculator.asString("5555555.1234567890") == "5555555.12")
    #expect(calculator.asString("55555555.1234567890") == "55555555.1")
    #expect(calculator.asString("555555555.1234567890") == "5.555555e8")
    #expect(calculator.asString("5555555555.1234567890") == "5.555555e9")
    #expect(calculator.asString("55555555555.1234567890") == "5.55555e10")
    #expect(calculator.asString("555555555555.1234567890") == "5.55555e11")
    #expect(calculator.asString("5555555555555.1234567890") == "5.55555e12")
    #expect(calculator.asString("55555555555555.1234567890") == "5.55555e13")
}
