// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
import SwiftGmp

@Test func testPrecisionTest() {
    let calculator = Calculator(precision: 20)

}
