// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
@testable import SwiftGmp

@Test func basics1TestRaw() {
    let calculator = Calculator(precision: 20)

    calculator.setPrecision(newPrecision: 40)
    calculator.evaluateString("1.1 * 1")
    #expect(calculator.string == "1.1")

    calculator.evaluateString("1 + 3 * 10")
    #expect(calculator.string == "31")

    calculator.evaluateString("1 + 2")
    #expect(calculator.string == "3")

    calculator.evaluateString("2 * 4")
    #expect(calculator.string == "8")

    calculator.evaluateString("10/2")
    #expect(calculator.string == "5")

    calculator.evaluateString("abs(-5.0)")
    #expect(calculator.string == "5")

    calculator.evaluateString("abs(3.14)")
    #expect(calculator.string == "3.14")

    calculator.evaluateString("abs(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("500 + 500")
    #expect(calculator.string == "1000")

    calculator.evaluateString("abs(-100.25)")
    #expect(calculator.string == "100.25")

    calculator.evaluateString("abs(12.5)")
    #expect(calculator.string == "12.5")

    calculator.evaluateString("153.4 - 153")
    #expect(calculator.string == "0.4")

    calculator.evaluateString("153.4 - 152")
    #expect(calculator.string == "1.4")

    calculator.evaluateString("153.4 - 142")
    #expect(calculator.string == "11.4")

    calculator.evaluateString("153.4 - 154")
    #expect(calculator.string == "-0.6")

    calculator.evaluateString("153.4 - 155")
    #expect(calculator.string == "-1.6")

    calculator.evaluateString("153.4 - 165")
    #expect(calculator.string == "-11.6")

    calculator.evaluateString("1 / 7")
    #expect(calculator.string == "0.14285714")

    calculator.evaluateString("10 %")
    #expect(calculator.string == "0.1")

    calculator.evaluateString("200 + 20 %")
    #expect(calculator.string == "240")

    calculator.evaluateString("100 + e %")
    #expect(calculator.string == "102.718281")

    calculator.evaluateString("0.1 %")
    #expect(calculator.string == "0.001")

    calculator.evaluateString("pi")
    #expect(calculator.string == "3.14159265")

    calculator.evaluateString("sqrt(4.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("sqrt(9.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("sqrt(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sqrt(16.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("sqrt(25.0)")
    #expect(calculator.string == "5")

    calculator.evaluateString("sqrt3(8.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("sqrt3(27.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("sqrt3(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sqrt3(64.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("sqrt3(125.0)")
    #expect(calculator.string == "5")

    calculator.evaluateString("zeta(2)")
    #expect(calculator.string == "1.64493406")

    calculator.evaluateString("zeta(3)")
    #expect(calculator.string == "1.20205690")

    calculator.evaluateString("zeta(4)")
    #expect(calculator.string == "1.08232323")

    calculator.evaluateString("zeta(5)")
    #expect(calculator.string == "1.03692775")

    calculator.evaluateString("zeta(6)")
    #expect(calculator.string == "1.01734306")

    calculator.evaluateString("zeta(7)")
    #expect(calculator.string == "1.00834927")

    calculator.evaluateString("zeta(8)")
    #expect(calculator.string == "1.00407735")

    calculator.evaluateString("zeta(9)")
    #expect(calculator.string == "1.00200839")

    calculator.evaluateString("ln(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("ln(2.7182818284590452)")
    #expect(calculator.string == "1")

    calculator.evaluateString("ln(7.3890560989306502)")
    #expect(calculator.string == "2")

    calculator.evaluateString("ln(20.08553692318766774)")
    #expect(calculator.string == "3")

    calculator.evaluateString("ln(54.59815003314423907)")
    #expect(calculator.string == "4")

    calculator.evaluateString("log10(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("log10(10.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("log10(100.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("log10(1000.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("log10(10000.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("log2(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("log2(2.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("log2(4.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("log2(8.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("log2(16.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("sqr(2.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("sqr(3.0)")
    #expect(calculator.string == "9")

    calculator.evaluateString("sqr(5.0)")
    #expect(calculator.string == "25")

    calculator.evaluateString("sqr(-4.0)")
    #expect(calculator.string == "16")

    calculator.evaluateString("sqr(10.0)")
    #expect(calculator.string == "100")

    calculator.evaluateString("exp(1.0)")
    #expect(calculator.string == "2.71828182")

    calculator.evaluateString("exp(2.0)")
    #expect(calculator.string == "7.38905609")

    calculator.evaluateString("exp(3.0)")
    #expect(calculator.string == "20.0855369")

    calculator.evaluateString("exp(0.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("exp(-1.0)")
    #expect(calculator.string == "0.36787944")

    calculator.evaluateString("exp10(0.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("exp10(1.0)")
    #expect(calculator.string == "10")

    calculator.evaluateString("exp10(2.0)")
    #expect(calculator.string == "100")

    calculator.evaluateString("exp10(3.0)")
    #expect(calculator.string == "1000")

    calculator.evaluateString("exp10(-1.0)")
    #expect(calculator.string == "0.1")

    calculator.evaluateString("0.0 ±")
    #expect(calculator.string == "0")

    calculator.evaluateString("0.0 ±")
    #expect(calculator.string == "0")

    calculator.evaluateString("5.0 ±")
    #expect(calculator.string == "-5")

    calculator.evaluateString("-3.14 ±")
    #expect(calculator.string == "3.14")

    calculator.evaluateString("0.0 ±")
    #expect(calculator.string == "0")

    calculator.evaluateString("100.0 ±")
    #expect(calculator.string == "-100")

    calculator.evaluateString("-50.0 ±")
    #expect(calculator.string == "50")

    calculator.evaluateString("cubed(2.0)")
    #expect(calculator.string == "8")

    calculator.evaluateString("cubed(3.0)")
    #expect(calculator.string == "27")

    calculator.evaluateString("cubed(-4.0)")
    #expect(calculator.string == "-64")

    calculator.evaluateString("cubed(5.0)")
    #expect(calculator.string == "125")

    calculator.evaluateString("cubed(-2.0)")
    #expect(calculator.string == "-8")

    calculator.evaluateString("rez(2.0)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("rez(4.0)")
    #expect(calculator.string == "0.25")

    calculator.evaluateString("rez(0.5)")
    #expect(calculator.string == "2")

    calculator.evaluateString("rez(10.0)")
    #expect(calculator.string == "0.1")

    calculator.evaluateString("rez(0.2)")
    #expect(calculator.string == "5")

    calculator.evaluateString("fac(0.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("fac(1.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("fac(2.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("sind(30)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("sind(45)")
    #expect(calculator.string == "0.70710678")

    calculator.evaluateString("sind(60)")
    #expect(calculator.string == "0.86602540")

    calculator.evaluateString("sind(90)")
    #expect(calculator.string == "1")

    calculator.evaluateString("sind(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sind(180)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sind(270)")
    #expect(calculator.string == "-1")

    calculator.evaluateString("cosd(30)")
    #expect(calculator.string == "0.86602540")

    calculator.evaluateString("cosd(45)")
    #expect(calculator.string == "0.70710678")

    calculator.evaluateString("cosd(60)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("cosd(90)")
    #expect(calculator.string == "0")

    calculator.evaluateString("tand(45)")
    #expect(calculator.string == "1")

    calculator.evaluateString("tand(60)")
    #expect(calculator.string == "1.73205080")

    calculator.evaluateString("tand(30)")
    #expect(calculator.string == "0.57735026")

    calculator.evaluateString("tand(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("asind(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("acosd(0)")
    #expect(calculator.string == "90")

    calculator.evaluateString("asind(0.5)")
    #expect(calculator.string == "30")

    calculator.evaluateString("acosd(0.5)")
    #expect(calculator.string == "60")

    calculator.evaluateString("atand(1)")
    #expect(calculator.string == "45")

    calculator.evaluateString("atand(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(1.5708)")
    #expect(calculator.string == "1")

    calculator.evaluateString("cos(0.5236)")
    #expect(calculator.string == "0.8660")

    calculator.evaluateString("sin(1.0472)")
    #expect(calculator.string == "0.8660")

    calculator.evaluateString("tan(0.7854)")
    #expect(calculator.string == "1")

    calculator.evaluateString("sin(2.3562)")
    #expect(calculator.string == "0.7071")

    calculator.evaluateString("cos(2.6180)")
    #expect(calculator.string == "-0.8660")

    calculator.evaluateString("sin(3.1416)")
    #expect(calculator.string == "0")

    calculator.evaluateString("cos(3.1416)")
    #expect(calculator.string == "-1")

    calculator.evaluateString("sin(3.6652)")
    #expect(calculator.string == "-0.5")

    calculator.evaluateString("cos(3.92699)")
    #expect(calculator.string == "-0.7071")

    calculator.evaluateString("sin(5.7596)")
    #expect(calculator.string == "-0.5")

    calculator.evaluateString("sin(6.2832)")
    #expect(calculator.string == "0")

    calculator.evaluateString("cos(4.7124)")
    #expect(calculator.string == "0")

    calculator.evaluateString("atan(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("atan(1.0)")
    #expect(calculator.string == "0.7854")

    calculator.evaluateString("acos(0.8660)")
    #expect(calculator.string == "0.5236")

    calculator.evaluateString("asin(0.5)")
    #expect(calculator.string == "0.5236")

    calculator.evaluateString("atan(-1.0)")
    #expect(calculator.string == "-0.7854")

    calculator.evaluateString("asin(0.8660)")
    #expect(calculator.string == "1.0472")

    calculator.evaluateString("acos(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(0.7854)")
    #expect(calculator.string == "0.7071")

    calculator.evaluateString("cos(1.5708)")
    #expect(calculator.string == "0.0")

    calculator.evaluateString("tan(1.0472)")
    #expect(calculator.string == "1.7321")

    calculator.evaluateString("sin(0.5236)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("tan(0.5236)")
    #expect(calculator.string == "0.5774")

    calculator.evaluateString("cos(1.0472)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("sin(2.0944)")
    #expect(calculator.string == "0.8660")

    calculator.evaluateString("tan(3.1416)")
    #expect(calculator.string == "0.0")

    calculator.evaluateString("sin(2.6180)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("cos(5.23599)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("cos(2.0944)")
    #expect(calculator.string == "-0.5")

    calculator.evaluateString("cos(5.7596)")
    #expect(calculator.string == "0.8660")

    calculator.evaluateString("asin(1.0)")
    #expect(calculator.string == "1.5708")

    calculator.evaluateString("acos(0.0)")
    #expect(calculator.string == "1.5708")

    calculator.evaluateString("acos(0.7071)")
    #expect(calculator.string == "0.7854")

    calculator.evaluateString("atan(0.5774)")
    #expect(calculator.string == "0.5236")

    calculator.evaluateString("sind(30)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("sind(45)")
    #expect(calculator.string == "0.707106781186548")

    calculator.evaluateString("sind(60)")
    #expect(calculator.string == "0.866025403784439")

    calculator.evaluateString("sind(90)")
    #expect(calculator.string == "1")

    calculator.evaluateString("sind(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sind(180)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sind(270)")
    #expect(calculator.string == "-1")

    calculator.evaluateString("cosd(30)")
    #expect(calculator.string == "0.866025403784439")

    calculator.evaluateString("cosd(45)")
    #expect(calculator.string == "0.707106781186548")

    calculator.evaluateString("cosd(60)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("cosd(90)")
    #expect(calculator.string == "0")

    calculator.evaluateString("tand(45)")
    #expect(calculator.string == "1")

    calculator.evaluateString("tand(60)")
    #expect(calculator.string == "1.73205080756888")

    calculator.evaluateString("tand(30)")
    #expect(calculator.string == "0.577350269189626")

    calculator.evaluateString("tand(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("asind(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("acosd(0)")
    #expect(calculator.string == "90")

    calculator.evaluateString("asind(0.5)")
    #expect(calculator.string == "30")

    calculator.evaluateString("acosd(0.5)")
    #expect(calculator.string == "60")

    calculator.evaluateString("atand(1)")
    #expect(calculator.string == "45")

    calculator.evaluateString("atand(0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(1.5708)")
    #expect(calculator.string == "0.999999999993253")

    calculator.evaluateString("cos(0.5236)")
    #expect(calculator.string == "0.866025403784439")

    calculator.evaluateString("sin(1.0472)")
    #expect(calculator.string == "0.866025403784439")

    calculator.evaluateString("tan(0.7854)")
    #expect(calculator.string == "0.999999999993253")

    calculator.evaluateString("sin(2.3562)")
    #expect(calculator.string == "0.707106781180780")

    calculator.evaluateString("cos(2.6180)")
    #expect(calculator.string == "-0.866025403780126")

    calculator.evaluateString("sin(3.1416)")
    #expect(calculator.string == "0.000002653589793")

    calculator.evaluateString("cos(3.1416)")
    #expect(calculator.string == "-0.999999999996479")

    calculator.evaluateString("sin(3.6652)")
    #expect(calculator.string == "-0.499999999990409")

    calculator.evaluateString("cos(3.92699)")
    #expect(calculator.string == "-0.707106781185333")

    calculator.evaluateString("sin(5.7596)")
    #expect(calculator.string == "-0.499999999997013")

    calculator.evaluateString("sin(6.2832)")
    #expect(calculator.string == "-0.000002653589793")

    calculator.evaluateString("cos(4.7124)")
    #expect(calculator.string == "-0.000003673205103")

    calculator.evaluateString("atan(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("atan(1.0)")
    #expect(calculator.string == "0.785398163397448")

    calculator.evaluateString("acos(0.8660)")
    #expect(calculator.string == "0.523624774609514")

    calculator.evaluateString("asin(0.5)")
    #expect(calculator.string == "0.523598775598299")

    calculator.evaluateString("atan(-1.0)")
    #expect(calculator.string == "-0.785398163397448")

    calculator.evaluateString("asin(0.8660)")
    #expect(calculator.string == "1.04717155298542")

    calculator.evaluateString("acos(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(0.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("sin(0.7854)")
    #expect(calculator.string == "0.707106781180780")

    calculator.evaluateString("cos(1.5708)")
    #expect(calculator.string == "-0.000003673205103")

    calculator.evaluateString("tan(1.0472)")
    #expect(calculator.string == "1.73205080756888")

    calculator.evaluateString("sin(0.5236)")
    #expect(calculator.string == "0.499999999999964")

    calculator.evaluateString("tan(0.5236)")
    #expect(calculator.string == "0.577350269189626")

    calculator.evaluateString("cos(1.0472)")
    #expect(calculator.string == "0.500000000000000")

    calculator.evaluateString("sin(2.0944)")
    #expect(calculator.string == "0.866025403784439")

    calculator.evaluateString("tan(3.1416)")
    #expect(calculator.string == "-0.000002653589793")

    calculator.evaluateString("sin(2.6180)")
    #expect(calculator.string == "0.499999999995347")

    calculator.evaluateString("cos(5.23599)")
    #expect(calculator.string == "0.500000000007557")

    calculator.evaluateString("cos(2.0944)")
    #expect(calculator.string == "-0.500000000000000")

    calculator.evaluateString("cos(5.7596)")
    #expect(calculator.string == "0.866025403785142")

    calculator.evaluateString("asin(1.0)")
    #expect(calculator.string == "1.57079632679490")

    calculator.evaluateString("acos(0.0)")
    #expect(calculator.string == "1.57079632679490")

    calculator.evaluateString("acos(0.7071)")
    #expect(calculator.string == "0.785398999044520")

    calculator.evaluateString("atan(0.5774)")
    #expect(calculator.string == "0.523598775234146")

}
