// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
@testable import SwiftGmp

@Test func basics3TestRaw() {
    let calculator = Calculator(precision: 20)
    var swiftGmp: SwiftGmp = SwiftGmp(withString: "0", bits: 100)
    var raw: Raw = Raw(mantissa: "0", exponent: 0, length: 10)
    var display: Display = Display(raw: Raw(mantissa: "0", exponent: 0, length: 10))
    let L = 10

    calculator.evaluateString("sqr(4.0)")
    #expect(calculator.string == "16")

    calculator.evaluateString("sqr(2.0)")
    #expect(calculator.string == "4")

    calculator.evaluateString("cubed(5.0)")
    #expect(calculator.string == "125")

    calculator.evaluateString("cubed(2.0)")
    #expect(calculator.string == "8")

    calculator.evaluateString("exp(1.0)")
    #expect(calculator.string == "2.7183")

    calculator.evaluateString("exp(2.0)")
    #expect(calculator.string == "7.3891")

    calculator.evaluateString("exp10(1.0)")
    #expect(calculator.string == "10")

    calculator.evaluateString("exp10(2.0)")
    #expect(calculator.string == "100")

    calculator.evaluateString("1.0 ±")
    #expect(calculator.string == "-1")

    calculator.evaluateString("-1.0 ±")
    #expect(calculator.string == "1")

    calculator.evaluateString("rez(2.0)")
    #expect(calculator.string == "0.5")

    calculator.evaluateString("rez(4.0)")
    #expect(calculator.string == "0.25")

    calculator.evaluateString("fac(5.0)")
    #expect(calculator.string == "120")

    calculator.evaluateString("fac(3.0)")
    #expect(calculator.string == "6")

    calculator.evaluateString("0")
    #expect(calculator.string == "0")

    calculator.evaluateString("pi")
    #expect(calculator.string == "3.1416")

    calculator.evaluateString("e")
    #expect(calculator.string == "2.7183")

    calculator.evaluateString("abs(-3.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("sqrt(9.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("sqrt3(8.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("sqrt(2.0)")
    #expect(calculator.string == "1.4142")

    calculator.evaluateString("zeta(3.0)")
    #expect(calculator.string == "1.2021")

    calculator.evaluateString("ln(1.0)")
    #expect(calculator.string == "0")

    calculator.evaluateString("ln(2.0)")
    #expect(calculator.string == "0.6931")

    calculator.evaluateString("log10(10.0)")
    #expect(calculator.string == "1")

    calculator.evaluateString("log10(100.0)")
    #expect(calculator.string == "2")

    calculator.evaluateString("log2(8.0)")
    #expect(calculator.string == "3")

    calculator.evaluateString("log2(16.0)")
    #expect(calculator.string == "4")

}
