// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
@testable import SwiftGmp

@Test func calculatorBcTest() {
    let calculator = Calculator(precision: 100)

    var swiftGmp, bc: SwiftGmp

    swiftGmp = calculator.asSwiftGmp("1 + 2 * 3")
    bc = calculator.asSwiftGmp("7")
    #expect(swiftGmp.similar(to: bc, precision: 1e-100))
    swiftGmp = calculator.asSwiftGmp("sin(sin(1))")
    bc = calculator.asSwiftGmp(".7456241416655578888931510704303837920502916466153667384568765179941524530955192236078652150794035668")
    #expect(swiftGmp.similar(to: bc, precision: 1e-100))
    swiftGmp = calculator.asSwiftGmp("4.5")
    bc = calculator.asSwiftGmp("4.5")
    #expect(swiftGmp.similar(to: bc, precision: 1e-100))
// MC = true
// DISPLAY = 4.5
// M+ = true
// DISPLAY = 4.5
// M+ = true
// DISPLAY = 4.5
// M+ = true
// DISPLAY = 4.5
// M+ = true
// DISPLAY = 4.5
// MR = true
// DISPLAY = 18
// C = 0
// MR = true
// DISPLAY = 18
// MC = true
// DISPLAY = 18
// MR = false
// DISPLAY = 18
    swiftGmp = calculator.asSwiftGmp("sqr(2)")
    bc = calculator.asSwiftGmp("4")
    #expect(swiftGmp.similar(to: bc, precision: 1e-100))
    // sqr(2) 5 --> bc = error
// C = 0
// 10 % = 0.1
}
