// Note: This file is automatically generated.
//       It will be overwritten sooner or later.

import Testing
@testable import SwiftGmp

@Test func calculatorTestRaw() {
    let calculator = Calculator(precision: 20)
    var swiftGmp: SwiftGmp = SwiftGmp(withString: "0", bits: 100)
    var raw: Raw = Raw(mantissa: "0", exponent: 0, length: 10)
    var display: Display = Display(raw: Raw(mantissa: "0", exponent: 0, length: 10))
    let L = 10

    calculator.evaluateString("1 + 2 * 3")
    #expect(calculator.string == "7")

    calculator.evaluateString("sin(sin(1))")
    #expect(calculator.string == "0.745624141665")

    calculator.evaluateString("4.5")
    #expect(calculator.string == "4.5")

// clearing memory, no change to the display
    calculator.evaluateString("sqr(2)")
    #expect(calculator.string == "4")

    calculator.evaluateString("sqr(2) 5")
    #expect(calculator.string == "5")

    calculator.evaluateString("10 %")
    #expect(calculator.string == "0.1")

}
